_BASE_: ../Base-bagtricks.yml

MODEL:
  BACKBONE:
    WITH_IBN: True
  DEVICE: 'cuda:0'
DATASETS:
  NAMES: ("VERIOCR",)
  TESTS: ("VERIOCR",)

SOLVER:
  MAX_EPOCH: 1

OUTPUT_DIR: logs/veriocr/bagtricks_R50-ibn

